import { Link, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { useEffect, useState } from 'react';
import Navbar from './components/Navbar.jsx';
import ProtectedRoute from './components/ProtectedRoute.jsx';
import QuestionCard from './components/QuestionCard.jsx';
import AnswerList from './components/AnswerList.jsx';
import { Loading, EmptyState, ErrorMessage } from './components/StateViews.jsx';
import { useAuth } from './context/AuthContext.jsx';
import { api } from './api/client.js';
import { CATEGORIES, formatCategory } from './utils/categories.js';
import { formatDate } from './utils/format.js';

function Home() { const { isAuthenticated } = useAuth(); return <main><section className="hero"><div className="hero-copy"><span className="eyebrow">Knowledge, shared with confidence</span><h1>Good questions deserve <em>expert answers.</em></h1><p>ExpertConnect brings curious people together with verified professionals who can help them move forward.</p><div className="actions"><Link className="btn btn-primary" to="/questions">Browse Questions</Link><Link className="btn btn-outline" to="/ask">Ask a Question</Link></div><div className="trust"><span>✓ Verified expert answers</span><span>• Practical knowledge</span></div></div><div className="hero-art"><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><div className="art-card"><span className="art-check">✓</span><small>EXPERT VERIFIED</small><h3>Answers you can trust.</h3><p>Real people. Relevant experience. Helpful advice.</p></div><div className="art-dot dot-one"/><div className="art-dot dot-two"/></div></section><section className="home-bottom"><div><span className="eyebrow">A community for better answers</span><h2>Make your next question count.</h2></div><div className="actions">{isAuthenticated ? <><Link className="btn btn-primary" to="/my-questions">My Questions</Link><Link className="btn btn-ghost" to="/questions">Browse Questions →</Link></> : <><Link className="btn btn-primary" to="/register">Join ExpertConnect</Link><Link className="btn btn-ghost" to="/expert/apply">Become an Expert →</Link></>}</div></section></main> }

function Login() { const { login }=useAuth(); const nav=useNavigate(), loc=useLocation(); const [form,setForm]=useState({email:'',password:''}),[busy,setBusy]=useState(false),[error,setError]=useState(null); const submit=async e=>{e.preventDefault();setBusy(true);setError(null);try{await login(form.email,form.password);nav(loc.state?.from||'/questions',{replace:true})}catch(x){setError(x)}finally{setBusy(false)}};return <main className="narrow"><span className="eyebrow">Welcome back</span><h1>Log in</h1><p className="muted">Continue the conversation.</p><ErrorMessage error={error}/><form className="panel form" onSubmit={submit}><label>Email<input required type="email" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input required type="password" autoComplete="current-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><button disabled={busy} className="btn btn-primary">{busy?'Signing in…':'Log in'}</button></form><p className="muted">New here? <Link to="/register">Create an account</Link></p></main> }

function Register() { const {register}=useAuth();const nav=useNavigate();const [form,setForm]=useState({name:'',email:'',password:''}),[busy,setBusy]=useState(false),[error,setError]=useState(null);const submit=async e=>{e.preventDefault();setBusy(true);setError(null);try{await register(form);nav('/login',{replace:true,state:{registered:true}})}catch(x){setError(x)}finally{setBusy(false)}};return <main className="narrow"><span className="eyebrow">Join the community</span><h1>Create your account</h1><p className="muted">Public registration creates a standard member account.</p><ErrorMessage error={error}/><form className="panel form" onSubmit={submit}><label>Name<input required maxLength="120" autoComplete="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input required type="email" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input required type="password" minLength="8" maxLength="100" autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><button disabled={busy} className="btn btn-primary">{busy?'Creating account…':'Register'}</button></form></main> }

function Questions(){const [items,setItems]=useState([]),[category,setCategory]=useState(''),[busy,setBusy]=useState(true),[error,setError]=useState(null);useEffect(()=>{let on=true;setBusy(true);(category?api.questions.byCategory(category):api.questions.list()).then(d=>{if(on)setItems(d)}).catch(e=>{if(on)setError(e)}).finally(()=>{if(on)setBusy(false)});return()=>{on=false}},[category]);return <main><div className="page-heading"><div><span className="eyebrow">Community Q&amp;A</span><h1>Questions</h1><p className="muted">Explore questions and learn from verified experts.</p></div><Link className="btn btn-primary" to="/ask">Ask a question</Link></div><div className="toolbar"><label>Category <select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{CATEGORIES.map(c=><option key={c} value={c}>{formatCategory(c)}</option>)}</select></label><span className="muted">{items.length} {items.length===1?'question':'questions'}</span></div><ErrorMessage error={error}/>{busy?<Loading label="Loading questions…"/>:items.length?<div className="grid">{items.map(q=><QuestionCard key={q.id} question={q}/>)}</div>:<EmptyState message="No questions in this category yet."/>}</main>}

function QuestionDetail(){const {id}=useParams(),{user}=useAuth(),nav=useNavigate();const [question,setQ]=useState(null),[answers,setA]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState(null),[editing,setEditing]=useState(false),[form,setForm]=useState({title:'',description:'',category:''});const refresh=async()=>{const [q,a]=await Promise.all([api.questions.byId(id),api.answers.forQuestion(id)]);setQ(q);setA(a);setForm({title:q.title,description:q.description,category:q.category})};useEffect(()=>{let live=true;Promise.all([api.questions.byId(id),api.answers.forQuestion(id)]).then(([q,a])=>{if(live){setQ(q);setA(a);setForm({title:q.title,description:q.description,category:q.category})}}).catch(setError).finally(()=>setBusy(false));return()=>{live=false}},[id]);const owner=user?.id===question?.askerId;const remove=async()=>{if(!window.confirm('Delete this question?'))return;try{await api.questions.remove(id);nav('/my-questions')}catch(e){setError(e)}};const save=async e=>{e.preventDefault();try{await api.questions.update(id,form);setEditing(false);await refresh()}catch(e){setError(e)}};if(busy)return <Loading/>;if(error)return <main><ErrorMessage error={error}/></main>;if(!question)return null;return <main className="detail"><Link className="back" to="/questions">← All questions</Link><article className="question-detail panel"><div className="question-meta"><span className="badge">{formatCategory(question.category)}</span><span className="muted">Asked by {question.askerName} · {formatDate(question.createdAt)}</span></div>{editing?<form className="form" onSubmit={save}><label>Title<input required minLength="5" maxLength="200" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Description<textarea required minLength="10" maxLength="5000" rows="7" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Category<select required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><div className="actions"><button className="btn btn-primary">Save changes</button><button type="button" className="btn btn-ghost" onClick={()=>setEditing(false)}>Cancel</button></div></form>:<><h1>{question.title}</h1><p className="question-body">{question.description}</p></>}{owner&&!editing&&<div className="actions owner-actions"><button className="btn btn-outline" onClick={()=>setEditing(true)}>Edit question</button><button className="btn btn-danger" onClick={remove}>Delete question</button></div>}</article><AnswerList question={question} answers={answers} onRefresh={refresh}/></main>}

function QuestionForm(){const nav=useNavigate(),{user}=useAuth(),loc=useLocation();const [items,setItems]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(null);const editing=Boolean(loc.state?.question);const [form,setForm]=useState(loc.state?.question||{title:'',description:'',category:''});const submit=async e=>{e.preventDefault();setBusy(true);try{const q=editing?await api.questions.update(form.id,{title:form.title,description:form.description,category:form.category}):await api.questions.create({title:form.title,description:form.description,category:form.category});nav(`/questions/${q.id}`,{replace:true})}catch(x){setError(x)}finally{setBusy(false)}};return <main className="narrow"><span className="eyebrow">Ask the community</span><h1>{editing?'Edit question':'Ask a question'}</h1><p className="muted">Be specific so the right people can help.</p><ErrorMessage error={error}/><form className="panel form" onSubmit={submit}><label>Title<input required minLength="5" maxLength="200" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Description<textarea required minLength="10" maxLength="5000" rows="8" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Category<select required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">Choose a category</option>{CATEGORIES.map(c=><option key={c} value={c}>{formatCategory(c)}</option>)}</select></label><button disabled={busy} className="btn btn-primary">{busy?'Saving…':editing?'Save changes':'Publish question'}</button></form></main>}

function MyQuestions(){const {user}=useAuth();const [items,setItems]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState(null);const load=()=>api.questions.byUser(user.id).then(setItems).catch(setError).finally(()=>setBusy(false));useEffect(()=>{load()},[user.id]);return <main><div className="page-heading"><div><span className="eyebrow">Your activity</span><h1>My questions</h1></div><Link className="btn btn-primary" to="/ask">Ask a question</Link></div><ErrorMessage error={error}/>{busy?<Loading/>:items.length?<div className="grid">{items.map(q=><QuestionCard key={q.id} question={q}/>)}</div>:<EmptyState message="You have not asked a question yet."/>}</main>}

function ExpertApply(){const [form,setForm]=useState({expertise:'',bio:'',experience:''}),[status,setStatus]=useState(null),[busy,setBusy]=useState(true),[error,setError]=useState(null);useEffect(()=>{api.experts.mine().then(list=>{if(list.length)setStatus([...list].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))[0])}).catch(setError).finally(()=>setBusy(false))},[]);const submit=async e=>{e.preventDefault();try{setStatus(await api.experts.apply({...form,experience:Number(form.experience)}))}catch(e){setError(e)}};return <main className="narrow"><span className="eyebrow">Share what you know</span><h1>Become an expert</h1><p className="muted">Applications are reviewed by an administrator.</p>{busy?<Loading/>:status?<section className="panel status-panel"><span className={`badge badge-${status.verificationStatus.toLowerCase()}`}>{status.verificationStatus}</span><h2>Application status</h2><p>{formatCategory(status.expertise)} · {status.experience} years experience</p></section>:<><ErrorMessage error={error}/><form className="panel form" onSubmit={submit}><label>Expertise category<select required value={form.expertise} onChange={e=>setForm({...form,expertise:e.target.value})}><option value="">Choose one</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label>Professional bio<textarea required minLength="20" maxLength="1000" rows="5" value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></label><label>Years of experience<input required type="number" min="0" max="70" value={form.experience} onChange={e=>setForm({...form,experience:e.target.value})}/></label><button className="btn btn-primary">Submit application</button></form></>}</main>}

function Admin(){const [rows,setRows]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState(null);const refresh=()=>api.experts.byStatus('PENDING').then(setRows).catch(setError).finally(()=>setBusy(false));useEffect(()=>{refresh()},[]);const decide=async(id,action)=>{try{await api.experts[action](id);await refresh()}catch(e){setError(e)}};return <main><span className="eyebrow">Administration</span><h1>Expert applications</h1><p className="muted">Review applicants waiting for verification.</p><ErrorMessage error={error}/>{busy?<Loading/>:rows.length?<div className="stack">{rows.map(a=><article className="panel application" key={a.id}><div><span className="badge">{formatCategory(a.expertise)}</span><h2>{a.userName}</h2><p>{a.bio}</p><small className="muted">{a.experience} years · Applied {formatDate(a.createdAt)}</small></div><div className="actions"><button className="btn btn-success" onClick={()=>decide(a.id,'approve')}>Approve</button><button className="btn btn-danger" onClick={()=>decide(a.id,'reject')}>Reject</button></div></article>)}</div>:<EmptyState message="No pending applications."/>}</main>}

function Profile(){const {user}=useAuth();return <main className="narrow"><span className="eyebrow">Your account</span><h1>Profile</h1><section className="panel profile"><div><span className="muted">Name</span><strong>{user?.name}</strong></div><div><span className="muted">Email</span><strong>{user?.email}</strong></div><div><span className="muted">Role</span><strong>{user?.role}</strong></div>{user?.role==='EXPERT'&&<div><span className="muted">Expert verification</span><strong>Verified</strong></div>}</section></main>}

function Missing(){return <main className="narrow"><h1>Page not found</h1><Link to="/questions">Browse questions</Link></main>}
function Guard({children,roles}){return <ProtectedRoute roles={roles}>{children}</ProtectedRoute>}
export default function App(){return <><Navbar/><Routes><Route path="/" element={<Home/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/questions" element={<Questions/>}/><Route path="/questions/:id" element={<QuestionDetail/>}/><Route path="/ask" element={<Guard><QuestionForm/></Guard>}/><Route path="/my-questions" element={<Guard><MyQuestions/></Guard>}/><Route path="/profile" element={<Guard><Profile/></Guard>}/><Route path="/expert/apply" element={<Guard><ExpertApply/></Guard>}/><Route path="/admin" element={<Guard roles={['ADMIN']}><Admin/></Guard>}/><Route path="*" element={<Missing/>}/></Routes><footer>ExpertConnect <span>· Practical knowledge, shared.</span></footer></>}
